spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.90:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: zhangfan@07171074
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
